(function() {var implementors = {};
implementors['hyper'] = ["<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/collections/trait.Mutable.html' title='collections::Mutable'>Mutable</a> for <a class='struct' href='hyper/header/struct.Headers.html' title='hyper::header::Headers'>Headers</a>","<a class='stability Experimental' title='Experimental'></a>impl&lt;K: <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> + <a class='trait' href='http://doc.rust-lang.org/nightly/collections/hash/trait.Hash.html' title='collections::hash::Hash'>Hash</a>&lt;S&gt;, V, S, H: <a class='trait' href='http://doc.rust-lang.org/nightly/collections/hash/trait.Hasher.html' title='collections::hash::Hasher'>Hasher</a>&lt;S&gt;&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/collections/trait.Mutable.html' title='collections::Mutable'>Mutable</a> for <a class='struct' href='http://doc.rust-lang.org/nightly/std/collections/hashmap/map/struct.HashMap.html' title='std::collections::hashmap::map::HashMap'>HashMap</a>&lt;K, V, H&gt;","<a class='stability Experimental' title='Experimental'></a>impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> + <a class='trait' href='http://doc.rust-lang.org/nightly/collections/hash/trait.Hash.html' title='collections::hash::Hash'>Hash</a>&lt;S&gt;, S, H: <a class='trait' href='http://doc.rust-lang.org/nightly/collections/hash/trait.Hasher.html' title='collections::hash::Hasher'>Hasher</a>&lt;S&gt;&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/collections/trait.Mutable.html' title='collections::Mutable'>Mutable</a> for <a class='struct' href='http://doc.rust-lang.org/nightly/std/collections/hashmap/set/struct.HashSet.html' title='std::collections::hashmap::set::HashSet'>HashSet</a>&lt;T, H&gt;","<a class='stability Experimental' title='Experimental'></a>impl&lt;K: <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> + <a class='trait' href='http://doc.rust-lang.org/nightly/collections/hash/trait.Hash.html' title='collections::hash::Hash'>Hash</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/collections/hash/sip/struct.SipState.html' title='collections::hash::sip::SipState'>SipState</a>&gt;, V&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/collections/trait.Mutable.html' title='collections::Mutable'>Mutable</a> for <a class='struct' href='http://doc.rust-lang.org/nightly/std/collections/lru_cache/struct.LruCache.html' title='std::collections::lru_cache::LruCache'>LruCache</a>&lt;K, V&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
